/* mapping between Builtin typer and a function implemented in C

["Int.+", builtin_int_add]
["Int.-", builtin_int_sub]
["Int.*", builtin_int_mul]
["Int./", builtin_int_div]
["Float.+", builtin_float_add]
["Float.-", builtin_float_sub]
["Float.*", builtin_float_mul]
["Float./", builtin_float_div]
["Float.to_string", ]
["Int.<", builtin_int_lt]
["Int.>", builtin_int_gt]
["Int.=", builtin_int_eq]
["Int.<=", builtin_int_leq]
["Int.>=", builtin_int_geq]
["String.=", builtin_str_eq]
["Sexp.=", ]
["Sexp.symbol", ]
["Sexp.string", ]
["Sexp.node", ]
["Sexp.integer", ]
["Sexp.float", ]
["Sexp.dispatch", ]
["IO.bind", ]
["IO.return", ]
["IO.run", ]
["File.open", ]
["File.stdout", ]
["File.write", ]
["File.read", ]
["Sys.cpu_time", ]
["Sys.exit", ]
*/
