/* mapping between Builtin typer and a function implemented in C

["Int.+", ]
["Int.-", ]
["Int.*", ]
["Int./", ]
["Float.+", ]
["Float.-", ]
["Float.*", ]
["Float./", ]
["Float.to_string", ]
["Int.<", ]
["Int.>", ]
["Int.=", ]
["Int.<=", ]
["Int.>=", ]
["String.=", ]
["Sexp.=", ]
["Sexp.symbol", ]
["Sexp.string", ]
["Sexp.node", ]
["Sexp.integer", ]
["Sexp.float", ]
["Sexp.dispatch", ]
["IO.bind", ]
["IO.return", ]
["IO.run", ]
["File.open", ]
["File.stdout", ]
["File.write", ]
["File.read", ]
["Sys.cpu_time", ]
["Sys.exit", ]
*/
