/* Builtin functions from builtin.typer to implement in c

	builtin_int_add
	builtin_int_sub
	builtin_int_mul
	builtin_int_div
	builtin_float_add
	builtin_float_sub
	builtin_float_mul
	builtin_float_div
	builtin_float_tostring
	builtin_int_lt
	builtin_int_gt
	builtin_int_eq
	builtin_int_leq
	builtin_int_geq
	builtin_str_eq
	builtin_sexp_eq
	builtin_sexp_symbol
	builtin_sexp_string
	builtin_sexp_node
	builtin_sexp_int
	builtin_sexp_float
	builtin_sexp_dispatch
	builtin_io_bind
	builtin_io_return
	builtin_io_run
	builtin_file_open
	builtin_file_stdout
	builtin_file_write
	builtin_file_read
	builtin_sys_cputime
	builtin_sys_exit
*/
